---
title: "1.0 Data Wrangling"
author: "Andrew Ingalls"
date: "3/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openxlsx)
library(tidyverse)
library(gt)

```


```{r Growth Wrangling, warning = FALSE}
#import excel sheet using openxlsx library
df_growth <- read.xlsx("../data/Mysis_Pilot.xlsx", sheet="Exp_1", detectDates=T)

#Summary Stats and first 10 rows to check for proper import
summary(df_growth)
head(df_growth)

#Remove unneeded columns from df_growth such as Time, Age, Outliers, 
#and Condition Factor
df_growth <- subset(df_growth, select = -c(Time, Age, 
                                        Possible.Outliers, Condition.Factor))

#rename columns for consistency & ease of use
colnames(df_growth) <- c("Date", "Tank", "Age_Category","Feed_Group",
                         "Length_mm","Mass_mg")

#add unique sample ID column for tracking and comparison
df_growth <- df_growth %>%
  add_column(Sample_ID =  seq(1001,1734,1), .before = "Date")

#changes data types and create factors where needed
#lapply allows iteration of function over a list (column names)
cols <- c("Tank", "Age_Category","Feed_Group")
df_growth[cols] <- lapply(df_growth[cols], factor)

#check: sapply allows iteration of function over df to show classes in matrix
sapply(df_growth,class)

#reorder age category factor levels
df_growth$Age_Category <- factor(df_growth$Age_Category, 
                                 levels = c("Three Months", "Five Months",
                                             "Six Months", "Eight Months", 
                                             "Nine Months","Twelve Months"))

#Check for NAs in dataset
df_growth[!complete.cases(df_growth),]

#create lists of 3 different periods of sample locations. 
#To be used to batch change sample locations to their final location
first_tank_locations <- c("7.C.4","7.C.5","7.C.6","7.C.7","7.C.8","7.C.9",
                    "7.C.10","7.C.11")
second_tank_locations <- c("7.B.3-4","7.C.3-4","7.C.1-2","7.C.5-6","7.C.7-8",
                       "7.C.9-10","7.E.9-10","7.C.11-12")
third_tank_locations <- c("7.E.3-4","7.E.1-2","7.D.7-8","7.E.11-12","7.D.1-2",
                    "7.D.3-4","7.E.9-10","7.D.5-6")

#batch change the tank locations based on the lists above which was the first 
#mass move of tanks (can be found in readme.md)
#!!! splice operator that allows us to use recode over the two lists of sample 
#locations, rather than just two individual sample locations
df_growth <- df_growth %>%
  mutate(Tank = recode(Tank, !!!setNames(third_tank_locations, first_tank_locations)))

#batch change again for the second mass move of tanks(can be found in readme.md)
df_growth <- df_growth %>%
  mutate(Tank = recode(Tank, !!!setNames(third_tank_locations, second_tank_locations)))

#Check all data wrangling performed.
summary(df_growth)
levels(df_growth$Tank)

```


```{r Survival Wrangling, warning = FALSE}
#import excel sheet for survival
df_survival <- read.xlsx("../data/Mysis_Pilot.xlsx", 
                       sheet="Survival Census (Progress)", detectDates=T)


#Remove columns that were just interim calculations in excel. Not needed
df_survival <- subset(df_survival, select=-c(Lost, Total, Male, Female, Unknown)) 

#rename columns for consistency
colnames(df_survival) <- c("Date", "Tank","Feed_Group", "Census")

#Same batch process explained in growth
df_survival <- df_survival %>%
  mutate(Tank = recode(Tank, !!!setNames(third_tank_locations, first_tank_locations)))

#batch change again for the second mass move of tanks(readme.md)
df_survival <- df_survival %>%
  mutate(Tank = recode(Tank, !!!setNames(third_tank_locations, second_tank_locations)))

#homogenize dates; survival was counted over two days for some census events
#lists for the events
first_collection_days <- c("2021-01-29", "2021-03-13", "2021-04-30")
second_collection_days <- c("2021-01-28", "2021-03-12", "2021-04-29")

#turn date into a character to allow for the replacement
df_survival$Date <- as.character(df_survival$Date)

#Same batch process as above to homogenize collection days for analysis
df_survival <- df_survival %>%
  mutate(Date = recode(Date, !!!setNames(first_collection_days, 
                                         second_collection_days)))
#back to date data type
df_survival$Date <- as.Date(df_survival$Date)

#Change Tank and Feed_Group features into Factors
df_survival$Tank <- factor(df_survival$Tank) 
df_survival$Feed_Group <- factor(df_survival$Feed_Group)

#check data wrangling
summary(df_survival)
head(df_survival)
```


```{r Sex Sort Wrangling, warning = FALSE}
df_sex_sort <- read.xlsx("../data/Mysis_Pilot.xlsx", 
                        sheet="Sexing", detectDates=T)

#remove time column
df_sex_sort <- subset(df_sex_sort, select = -Time)

#rename columns for consistency
colnames(df_sex_sort) <- c("Date", "Tank", "Feed_Group", "Female", "Male", "Unknown")

#Factor Tank and Group
df_sex_sort$Tank <- factor(df_sex_sort$Tank)
df_sex_sort$Feed_Group <- factor(df_sex_sort$Feed_Group)

#check stats and wrangling
summary(df_sex_sort)
head(df_sex_sort)

```


```{r Fecundity Wrangling,  warning = FALSE}

```

```{r Nutrition Wrangling, warning = FALSE}

font_import(paths="../data/")



Product <- c("Mysis", "Gemma")
Protein <-c(.119,.57)
Lipid <- c(.023,.15)
Ash <- c(NA,.105)
Fiber <- c(.005,.002)
Fatty_Acid <- c(.014,.03)
Moisture <- c(.845, NA)

nutrition <- data.frame(Product,Protein,Lipid,Ash,Fiber,Fatty_Acid,Moisture)

nutrition_long<- nutrition %>%
  pivot_longer(.,Protein:Moisture,names_to = "Nutrient", values_to = "Percentage")

ggplot(nutrition_long, aes(x=Nutrient,y=Percentage, fill=Product))+geom_col(position="dodge")

#Create table using grammar of tables package

gt_table <-nutrition %>% gt()
  
#Change column labels
gt_table <- gt_table %>%
  cols_label(
    Product = md("Product"),
    Protein = md("Protein"),
    Lipid  = md("Lipid"),
    Ash =  md("Ash"),
    Fiber = md("Fiber"),
    Fatty_Acid =  md("Fatty Acid"),
    Moisture = md("Moisture")
  )

#create header table
gt_table <- gt_table %>%
  tab_header (
    title = "Nutrition of Mysis Shrimp vs. Skretting Gemma",
    subtitle = "Macronutrient Percentage from Respective Companies"
  )

#format percentage
gt_table <- gt_table %>%
  fmt_percent(
   c(Protein,Lipid,Ash,Fiber,Fatty_Acid,Moisture),
   rows = everything(),
   decimals = 1
  )
#format alignment
gt_table <- gt_table %>%
  cols_align(
    align = "left",
    columns = c("Product")
  ) %>%
  cols_align(
    align = "center",
    columns =  c("Protein","Lipid","Ash","Fiber","Fatty_Acid","Moisture")
  )%>%
  cols_width(
    c("Product","Protein","Lipid","Ash","Fiber","Fatty_Acid","Moisture") ~ px(100)
  ) %>%
  opt_row_striping()

#Adding footnote
gt_table <- gt_table %>%
  tab_footnote(
    footnote = "Data not provided by manufacturer",
    locations = cells_body(
      columns = "Ash",
      rows = is.na(Ash)
    )
  ) %>%
  tab_footnote(
    footnote = "Data not provided by manufacturer",
    locations = cells_body(
      columns = "Moisture",
      rows = is.na(Moisture)
    )
  )

#Text font, coloring, sizing, some borders gt is fun!

gt_table <- gt_table %>%
#title styling
  tab_style(
    style = list(
      cell_text(
        size =px(30),
        weight = "normal",
        align = "left",
        font = "Bloomsbury"
      )
    ),
    locations = list(
      cells_title(groups = "title")
    )
  ) %>%
#subtitle styling
  tab_style(
    style = list(
      cell_text(
        size =px(15),
        align = "left"
      )
    ),
    locations = list(
      cells_title(groups = "subtitle")
    ) 
  ) %>% 
#cell borders
 tab_style(
  style = list(
   cell_text(
    size = px(15)
   ),
   cell_borders(
    sides = c("bottom", "top"),
    color = 'black',
    weight = px(1)
   )
  ),
  locations = list(
   cells_body(gt::everything())
  )
 ) %>%
#Product styling  
tab_style(
  style = list(
   cell_text(
    font = "Bloomsbury", size = px(20), 
    weight = "bold",
    color = "#2f5375")
  ),
  location = list(
   cells_body(columns = c(Product))
  )
 ) 

gtsave(gt_table,"gt_table.png")

```

