---
title: "1.0 Data Wrangling"
author: "Andrew Ingalls"
date: "3/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openxlsx)
library(tidyverse)
library(gt)

```


```{r Growth Wrangling, warning = FALSE}
#import excel sheet using openxlsx library
df_growth <- read.xlsx("../data/Mysis_Pilot.xlsx", sheet="Exp_1", detectDates=T)

summary(df_growth)
head(df_growth)

df_growth <- subset(df_growth, select = -c(Time,  
                                        Possible.Outliers, Condition.Factor))

colnames(df_growth) <- c("Date", "Tank_Location", "Age","Age_Category","Feed_Group",
                         "Length_mm","Mass_mg")

#add unique sample ID column for tracking and comparison
df_growth <- df_growth %>%
  add_column(Sample_ID =  seq(1001,1734,1), .before = "Date")

#changes data types and create factors where needed
#lapply allows iteration of function over a list (column names)
cols <- c("Tank_Location", "Age_Category","Feed_Group")
df_growth[cols] <- lapply(df_growth[cols], factor)

#sapply allows iteration of function over df to show classes in matrix
#allows us to check if classes are correct
sapply(df_growth,class)

#reorder age category factor levels
df_growth$Age_Category <- factor(df_growth$Age_Category, 
                                 levels = c("Three Months", "Five Months",
                                             "Six Months", "Eight Months", 
                                             "Nine Months","Twelve Months"))

#Check for NAs in dataset
df_growth[!complete.cases(df_growth),]

#To be used to batch change sample locations to their final location
first_tank_locations <- c("7.C.4","7.C.5","7.C.6","7.C.7","7.C.8","7.C.9",
                    "7.C.10","7.C.11")
second_tank_locations <- c("7.B.3-4","7.C.3-4","7.C.1-2","7.C.5-6","7.C.7-8",
                       "7.C.9-10","7.E.9-10","7.C.11-12")
third_tank_locations <- c("7.E.3-4","7.E.1-2","7.D.7-8","7.E.11-12","7.D.1-2",
                    "7.D.3-4","7.E.9-10","7.D.5-6")

#batch change the tank locations based on the lists above which was the first 
#!!! splice operator allows us to use recode over the two lists of sample 
#locations, rather than just two individual sample locations
df_growth <- df_growth %>%
  mutate(Tank_Location = recode(Tank_Location, !!!setNames(third_tank_locations, first_tank_locations)))

df_growth <- df_growth %>%
  mutate(Tank_Location = recode(Tank_Location, !!!setNames(third_tank_locations, second_tank_locations)))

summary(df_growth)
levels(df_growth$Tank_Location)

```


```{r Survival Wrangling, warning = FALSE}
df_survival <- read.xlsx("../data/Mysis_Pilot.xlsx", 
                       sheet="Survival Census (Progress)", detectDates=T)

df_survival <- subset(df_survival, select=-c(Lost, Total, Male, Female, Unknown)) 

colnames(df_survival) <- c("Date", "Tank_Location","Feed_Group", "Census")

df_survival <- df_survival %>%
  mutate(Tank_Location = recode(Tank_Location, !!!setNames(third_tank_locations, first_tank_locations)))

df_survival <- df_survival %>%
  mutate(Tank_Location = recode(Tank_Location, !!!setNames(third_tank_locations, second_tank_locations)))

#homogenize dates; survival was counted over two days for some census events
#lists for the events
first_collection_days <- c("2021-01-29", "2021-03-13", "2021-04-30")
second_collection_days <- c("2021-01-28", "2021-03-12", "2021-04-29")

df_survival$Date <- as.character(df_survival$Date)
df_survival <- df_survival %>%
  mutate(Date = recode(Date, !!!setNames(first_collection_days, 
                                         second_collection_days)))
df_survival$Date <- as.Date(df_survival$Date)

df_survival$Tank_Location <- factor(df_survival$Tank_Location) 
df_survival$Feed_Group <- factor(df_survival$Feed_Group)

summary(df_survival)
head(df_survival)
```


```{r Sex Sort Wrangling, warning = FALSE}
df_sex_sort <- read.xlsx("../data/Mysis_Pilot.xlsx", 
                        sheet="Sexing", detectDates=T)

df_sex_sort <- subset(df_sex_sort, select = -Time)

colnames(df_sex_sort) <- c("Date", "Tank_Location", 
                           "Feed_Group", "Female", "Male", "Unknown")

df_sex_sort$Tank_Location <- factor(df_sex_sort$Tank_Location)
df_sex_sort$Feed_Group <- factor(df_sex_sort$Feed_Group)

summary(df_sex_sort)
head(df_sex_sort)

```


```{r Fecundity Wrangling,  warning = FALSE}
df_fecundity<-read.xlsx("../data/Mysis_Pilot.xlsx", 
                        sheet="Exp 2", detectDates=T)

colnames(df_fecundity) <- c("Sample_ID", "Date", "Feed_Group", 
                            "Embryo_Output", "Viable_Embryos")

df_fecundity$Sample_ID <- factor(df_fecundity$Sample_ID)
df_fecundity$Feed_Group <- factor(df_fecundity$Feed_Group)

summary(df_fecundity)
head(df_fecundity)

```

```{r Nutrition Wrangling, warning = FALSE}

#Create lists of values for dataframe based on manufacturers packaging
product <- c("Mysis", "Gemma")
protein <- c(.119,.57)
lipid <- c(.023,.15)
ash <- c(NA,.105)
fiber <- c(.005,.002)
fatty_acid <- c(.014,.03)
moisture <- c(.845, NA)

product_nutrition <- data.frame(product, protein, lipid, ash, 
                                fiber, fatty_acid, moisture)

#Create table using grammar of tables package
nutrition_table <- product_nutrition %>% gt()
  
#Change column labels
nutrition_table <- nutrition_table %>%
  cols_label(
    product = md("Product"),
    protein = md("Protein"),
    lipid  = md("Lipid"),
    ash =  md("Ash"),
    fiber = md("Fiber"),
    fatty_acid =  md("Fatty Acid"),
    moisture = md("Moisture")
  )

#create header information for table
nutrition_table <- nutrition_table %>%
  tab_header (
    title = "Nutrition of Mysis Shrimp vs. Skretting Gemma",
    subtitle = "Macronutrient Percentage from Respective Companies"
  )

#format values into percentage
nutrition_table <- nutrition_table %>%
  fmt_percent(
   c(protein, lipid, ash, fiber, fatty_acid, moisture),
   rows = everything(),
   decimals = 1
  )

#format column alignment
nutrition_table <- nutrition_table %>%
  cols_align(
    align = "left",
    columns = c("product")
  ) %>%
  cols_align(
    align = "center",
    columns =  c("protein", "lipid", "ash", 
                 "fiber", "fatty_acid", "moisture")
  ) %>%
  cols_width(
    c("product", "protein", "lipid", "ash", "fiber", 
      "fatty_acid", "moisture") ~ px(100)
  ) %>%
  opt_row_striping()

#Add footnote to explain missing data
nutrition_table <- nutrition_table %>%
  tab_footnote(
    footnote = "Data not provided by manufacturer",
    locations = cells_body(
      columns = "ash",
      rows = is.na(ash)
    )
  ) %>%
  tab_footnote(
    footnote = "Data not provided by manufacturer",
    locations = cells_body(
      columns = "moisture",
      rows = is.na(moisture)
    )
  )

#font, coloring, sizing, some borders
nutrition_table <- nutrition_table %>%
  tab_style( #title styling
    style = list(
      cell_text(
        size = px(30),
        weight = "normal",
        align = "left"
      )
    ),
    locations = list(
      cells_title(groups = "title")
    )
  ) %>%
  tab_style( #subtitle styling
    style = list(
      cell_text(
        size = px(15),
        align = "left"
      )
    ),
    locations = list(
      cells_title(groups = "subtitle")
    ) 
  ) %>% 
 tab_style( #cell borders
  style = list(
   cell_text(
    size = px(15)
   ),
   cell_borders(
    sides = c("bottom", "top"),
    color = 'black',
    weight = px(1)
   )
  ),
  locations = list(
   cells_body(gt::everything())
  )
 ) %>%
tab_style( #Product styling 
  style = list(
   cell_text(
    size = px(20), 
    weight = "bold",
    color = "#2f5375")
  ),
  location = list(
   cells_body(columns = c(product))
  )
 ) 

gtsave(nutrition_table,"nutrition_table.png")

```

